envoy:
  world: world
  region: envoy-drop
  cooldown: 60 # In minutes
  duration: 600 # In seconds
  spawning:
    players-required: 4
    ratio: .25
    round-up: true
warning-times: # In seconds
  - 600
  - 300
  - 180
  - 60
  - 10
  - 3
  - 2
  - 1
world-broadcast-list:
  - "*" # Use * for all worlds and just the world name for a specific world