envoy:
  world: world
  region: envoy-drop
  cooldown: 1h
  duration: 10m
  spawning:
    players-required: 4
    ratio: .25
    round-up: true
warning-times: # ex: 1h, 30m (MUST USE COMMA-SPACE)
  - 10m
  - 5m
  - 3m
  - 1m
  - 10s
  - 3s
  - 2s
  - 1s