main: me.schooltests.divergentenvoy.DivergentEnvoy
name: DivergentEnvoy
version: "1.0.0"
author: Itzdlg (SchoolTests)
load: postworld
commands:
  envoy:
    usage: /envoy <start|end|reload>
    description: Manage the DivergentEnvoy plugin